import Head from 'next/head'
import web3 from './web3'
import Link from 'next/link'
import abi from '../utils/abi.json'
import { useEffect, useState } from 'react'
import { Card, Button } from 'semantic-ui-react'
import Layout from '../components/Layout'
export default function Home() {
  const [campaigns, setCampaigns] = useState([])
  const getCampaigns = async () => {
    const campaign = new web3.eth.Contract(
      abi,
      '0xB20f2B24d5040770495b17007715efdDA5448554'
    )

    const allCampaigns = await campaign.methods.getDeployedCampaigns().call()
    setCampaigns(allCampaigns)
  }
  const seeAllCampaigns = () => {
    const myCampaigns = campaigns.map((address) => {
      return {
        header: address,
        description: (
          <Link href={`/campaigns/${address}`}>
            <a>view campaign</a>
          </Link>
        ),
        fluid: true,
      }
    })
    return myCampaigns
  }
  useEffect(() => {
    getCampaigns().catch((err) => {})
  }, [])
  return (
    <div>
      <Head>
        <title>Kickstart App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <h3>Open Campaigns</h3>
        <Link href='/campaigns/new'>
          <a>
            <Button
              floated='right'
              icon='plus'
              content='Create Campaign'
              primary
            />
          </a>
        </Link>
        <Card.Group items={seeAllCampaigns()} />
      </Layout>
    </div>
  )
}
